// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/**
 * Opções padrão de Firebase para a aplicação MediaHub.
 * Ficheiro auto-gerado pela FlutterFire CLI.
 * Contém configurações para múltiplas plataformas (web, Android, iOS, macOS, Windows).
 */
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzejDUqzBuyliNcMr6oqHM1Sbt94hYXAg',
    appId: '1:382178034614:web:4935a4655d50f8f6c97717',
    messagingSenderId: '382178034614',
    projectId: 'mediahub-eea2e',
    authDomain: 'mediahub-eea2e.firebaseapp.com',
    storageBucket: 'mediahub-eea2e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAcCeYiUBnwYgGp-J-QpHUJ3b9JYduzzg',
    appId: '1:382178034614:android:1729a6d3365dd7eac97717',
    messagingSenderId: '382178034614',
    projectId: 'mediahub-eea2e',
    storageBucket: 'mediahub-eea2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAzBs04uPq3mO2i-7RMle12YmjQJ6VMc8',
    appId: '1:382178034614:ios:a0916a41724f3316c97717',
    messagingSenderId: '382178034614',
    projectId: 'mediahub-eea2e',
    storageBucket: 'mediahub-eea2e.firebasestorage.app',
    iosBundleId: 'com.example.mediaHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAzBs04uPq3mO2i-7RMle12YmjQJ6VMc8',
    appId: '1:382178034614:ios:a0916a41724f3316c97717',
    messagingSenderId: '382178034614',
    projectId: 'mediahub-eea2e',
    storageBucket: 'mediahub-eea2e.firebasestorage.app',
    iosBundleId: 'com.example.mediaHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzejDUqzBuyliNcMr6oqHM1Sbt94hYXAg',
    appId: '1:382178034614:web:ac53d76fccfbd9e2c97717',
    messagingSenderId: '382178034614',
    projectId: 'mediahub-eea2e',
    authDomain: 'mediahub-eea2e.firebaseapp.com',
    storageBucket: 'mediahub-eea2e.firebasestorage.app',
  );
}
